Output ./assets/clever-f.gif
Set Shell "zsh"
Set Theme "TokyoNightStorm"
Set FontFamily "CaskaydiaCove Nerd Font"
Set FontSize 30
Set Width 1500
Set Height 900
Set Padding 10
Set TypingSpeed 0.1

Hide
Type@0ms "nvim lua/nvim-submode/init.lua"
Enter
Type@0ms ":lua require('keycastr').enable()" Enter
Type@0ms ":so" Enter
Sleep 5.0
Show

Sleep 2.0
Type "fr"
Sleep 1.7
Type "f"
Sleep 1.7
Type "F"
Sleep 1.7

Type ";"
Sleep 1.7
Type ","
Sleep 1.7

Escape
Sleep 2.0
Hide
Type@0ms ":qa!" Enter
