Output ./assets/fizzbuzz.gif
Set Shell "zsh"
Set Theme "TokyoNightStorm"
Set FontFamily "CaskaydiaCove Nerd Font"
Set FontSize 20
Set Width 1500
Set Height 900
Set Padding 10
Set TypingSpeed 0.1

Hide
Type@0ms "nvim"
Enter
Type@0ms ":1"
Enter
Type@0ms "0"
Type@0ms ":lua require('keycastr').enable()" Enter
Sleep 5.0
Show
Sleep 2.0
Type "i*"
Sleep 2.0
Type "f"
Sleep 2.0
Type "15f"
Sleep 1.7
Type "2f"
Sleep 1.7

Escape
Sleep 2.0
Hide
Type@0ms ":qa!" Enter
